import React from "react";
import type { Workspace } from "../../shared/useWorkspace";
import { FactView, Proposals } from "../../shared/clinical";
import { Icon } from "../../shared/ui/Icon";
import { StatusBadge } from "../../shared/ui/StatusBadge";
import { humanizeClinicalText, type Fact } from "../../shared/types";
export type IntakeProps = Omit<Workspace, "session"> & { session: NonNullable<Workspace["session"]>; changeStep: (step: "intake" | "facts") => void; newFact: (fact?: Fact) => void };
export function IntakeStep({ props, pending }: { props: IntakeProps; pending: number }) {
  const activeJob = !!props.job && ["queued", "running"].includes(props.job.status);
  return <div className="focused-layout focused-layout--intake"><section className="panel conversation-panel">
    <div className="assistant-heading"><span className="assistant-mark"><Icon name="spark" /></span><div><span className="eyebrow">ผู้ช่วยรับข้อมูล</span><h2>สนทนาและรวบรวมข้อมูล</h2><p className="supporting-text">ข้อความจากผู้ช่วยจะไม่กลายเป็นข้อมูลเคสจนกว่าคุณจะตรวจ</p></div><StatusBadge tone={props.caps?.provider === "mock-v2" ? "warning" : "info"}>{props.caps?.provider === "mock-v2" ? "โหมดออฟไลน์" : "รอตรวจโมเดลจริง"}</StatusBadge></div>
    {pending ? <button className="proposal-notice" onClick={() => props.changeStep("facts")}><span className="proposal-notice__icon"><Icon name="alert" /></span><span><strong>มีข้อมูลจากผู้ช่วยรอตรวจ {pending} รายการ</strong><small>เปิดเพื่อตรวจค่าและยืนยันก่อนบันทึก</small></span><Icon name="arrow" /></button> : null}
    <div className="conversation" aria-label="ประวัติการสนทนา">{!props.runs.length ? <div className="empty-state empty-state--conversation"><span><Icon name="spark" /></span><h3>เริ่มจากอาการสำคัญ</h3><p>ลองพิมพ์ “ผู้ป่วยไอมา 2 วัน มีไข้ต่ำ” หรือถามผู้ช่วยว่าควรถามอะไรต่อ</p></div> : props.runs.map((run) => <article className="turn" key={run.run_id}>
      <div className="message-row message-row--user"><div className="message message--user"><span>คุณ</span><p>{run.user_text}</p></div><span className="message-avatar message-avatar--user" aria-hidden="true">{props.session.subject.slice(0, 1).toUpperCase()}</span></div>
      <div className="message-row"><span className="message-avatar" aria-hidden="true"><Icon name="spark" size={16} /></span><div className="message message--assistant"><div><span className="eyebrow">ผู้ช่วยรับข้อมูล</span><StatusBadge tone={run.status === "COMPLETED" ? "success" : "warning"}>{run.status === "COMPLETED" ? "ตอบแล้ว" : "ต้องตรวจสอบ"}</StatusBadge></div><p>{humanizeClinicalText(run.response)}</p>{run.status === "COMPLETED" ? <button className="button button--text button--speak" onClick={() => props.speak(humanizeClinicalText(run.response), run.run_id)}><Icon name="volume" />อ่านคำตอบ</button> : null}</div></div>
    </article>)}</div>
    {!props.message ? <div className="quick-prompts" aria-label="ข้อความแนะนำ"><span>ลองถามผู้ช่วย</span><button type="button" onClick={() => props.setMessage("จากข้อมูลที่มี ควรถามอะไรต่อเพื่อให้รับเคสครบถ้วน?")}>ควรถามอะไรต่อ</button><button type="button" onClick={() => props.setMessage("ช่วยสรุปข้อมูลที่ยืนยันแล้วของเคสนี้แบบสั้น")}>สรุปข้อมูลที่มี</button><button type="button" onClick={() => props.setMessage("ช่วยตรวจว่าข้อมูลสำคัญส่วนใดยังขาดอยู่")}>ตรวจข้อมูลที่ขาด</button></div> : null}
    <div className="composer"><label className="sr-only" htmlFor="assistant-message">ข้อความถึงผู้ช่วย</label><textarea id="assistant-message" aria-label="ข้อความถึงผู้ช่วย" placeholder="พิมพ์ข้อมูล อาการ หรือคำถามที่ต้องการให้ผู้ช่วยช่วยต่อ… (กด Ctrl+Enter เพื่อส่ง)" value={props.message} onChange={(event) => props.setMessage(event.target.value)} onKeyDown={(event) => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") { event.preventDefault(); if (!props.busy && props.message.trim() && !activeJob) props.startRun("conversation"); } }} /><div className="composer__footer"><div className="composer__tools"><button className={`button button--icon ${props.voiceState === "recording" ? "button--recording" : ""}`} aria-label={props.voiceState === "recording" ? "หยุดและถอดเสียง" : props.voiceState === "transcribing" ? "กำลังถอดเสียง" : "กดพูด"} title="กดพูด" disabled={!props.caps?.speech || (props.busy && props.voiceState === "idle")} onClick={props.record}>{props.voiceState === "recording" ? <Icon name="stop" /> : <Icon name="mic" />}</button><span>{props.caps?.speech ? (props.voiceState === "recording" ? "กำลังบันทึกเสียง" : props.voiceState === "transcribing" ? "กำลังถอดเสียง" : "พิมพ์หรือกดพูด") : "พิมพ์ข้อความได้ทันที"}</span></div><button className="button button--primary button--send" aria-label="ส่งข้อความ" disabled={props.busy || !props.message.trim() || activeJob} onClick={() => props.startRun("conversation")}>ส่งให้ผู้ช่วย <Icon name="arrow" /></button></div></div>
    {!props.caps?.speech ? <p className="voice-fallback">ยังไม่ตั้งค่าถอดเสียง การสนทนาด้วยข้อความใช้งานได้ครบทุกขั้นตอน</p> : null}<button className="button button--text stop-audio" onClick={props.stopAudio}><Icon name="volume" />หยุดอ่านเสียง</button>
  </section><aside className="context-rail"><section className="panel compact-summary"><span className="eyebrow">ข้อมูลที่พร้อมใช้</span><div className="summary-number"><strong>{props.facts.length}</strong><span>รายการยืนยันแล้ว</span></div>{props.facts.slice(0, 3).map((fact) => <FactView key={fact.event_id} fact={fact} />)}{props.facts.length > 3 ? <p className="supporting-text">และอีก {props.facts.length - 3} รายการ</p> : null}<button className="button button--secondary button--full" onClick={() => props.changeStep("facts")}>เปิดข้อมูลทั้งหมด</button></section><section className="panel clinical-note"><Icon name="lock" /><div><strong>บุคลากรเป็นผู้ควบคุม</strong><p>ทุกข้อเสนอและร่างต้องผ่านการตรวจยืนยันก่อนใช้งาน</p></div></section></aside></div>;
}

export function FactsStep({ props }: { props: IntakeProps }) {
  const pendingRuns = props.runs.filter((run) => run.case_revision === props.current?.case_revision && run.proposals.some((proposal) => proposal.proposal_id));
  const conflicts = props.facts.filter((fact) => fact.conflicts_with_event_ids?.length);
  const confirmed = props.facts.filter((fact) => !fact.conflicts_with_event_ids?.length);
  return <div className="facts-workspace">
    <section className="section-intro"><div><span className="eyebrow">ตรวจทานก่อนบันทึก</span><h2>ข้อมูลเคส</h2><p>ข้อเสนอจากผู้ช่วยและข้อมูลที่แก้ไขจะไม่ถูกใช้จนกว่าบุคลากรจะยืนยัน</p></div><button className="button button--secondary" onClick={() => props.newFact()}><Icon name="plus" />เพิ่มข้อมูลด้วยตัวเอง</button></section>
    {pendingRuns.length ? <section className="review-zone"><div className="zone-heading"><span className="zone-icon zone-icon--warning"><Icon name="alert" /></span><div><h3>รอตรวจ {pendingRuns.reduce((sum, run) => sum + run.proposals.length, 0)} รายการ</h3><p>ตรวจประเภท ค่า และหน่วยก่อนบันทึกแบบชุด</p></div></div>{pendingRuns.map((run) => <Proposals key={run.run_id} run={run} onDirty={(value) => props.trackDirty(run.run_id, value)} revision={props.current!.case_revision} act={props.act} />)}</section> : <section className="completion-card"><span><Icon name="check" /></span><div><h3>ตรวจข้อมูลเรียบร้อย</h3><p>ข้อมูลที่ยืนยันแล้วพร้อมใช้สร้างร่างส่งต่อ</p></div></section>}
    {conflicts.length ? <section className="review-zone review-zone--danger"><div className="zone-heading"><span className="zone-icon zone-icon--danger"><Icon name="alert" /></span><div><h3>ต้องตรวจความสอดคล้อง</h3><p>ข้อมูลต่อไปนี้ขัดแย้งกับข้อมูลอื่นในเคส</p></div></div><div className="fact-grid">{conflicts.map((fact) => <FactView key={fact.event_id} fact={fact} onEdit={props.newFact} />)}</div></section> : null}
    <section className="panel confirmed-zone"><div className="section-heading"><div><span className="eyebrow">พร้อมใช้สร้างร่าง</span><h2>ข้อมูลที่ยืนยันแล้ว</h2></div><StatusBadge tone="success">{confirmed.length} รายการ</StatusBadge></div>{confirmed.length ? <div className="fact-grid">{confirmed.map((fact) => <FactView key={fact.event_id} fact={fact} onEdit={props.newFact} />)}</div> : <div className="empty-state empty-state--compact"><Icon name="file" size={28} /><h3>ยังไม่มีข้อมูลยืนยัน</h3><p>กลับไปรับข้อมูลหรือเพิ่มข้อมูลด้วยตัวเอง</p></div>}</section>
  </div>;
}

