import React from "react";
import type { Capability, Case, Draft, Fact, Job, Run, Session } from "../types";
import { handoffLabels, humanizeClinicalText } from "../types";
import type { ClinicalWorkspaceStep } from "../workflow";
import { clinicalSteps, pendingProposalCount, stepState } from "../workflow";
import { FactEditor, FactView, Proposals, Review, StatusBadge } from "../components/clinical";
import { History } from "../components/system";
import { Icon } from "../components/Icon";
import { SideSheet } from "../components/SideSheet";

export type CasesPageProps = {
  cases: Case[]; current: Case | null; facts: Fact[]; runs: Run[]; drafts: Draft[]; session: Session; caps: Capability | null;
  step: ClinicalWorkspaceStep; changeStep: (step: ClinicalWorkspaceStep) => void;
  query: string; setQuery: (value: string) => void; caseStatus: string; setCaseStatus: (value: string) => void; nextOffset: number | null;
  newCaseOpen: boolean; setNewCaseOpen: (value: boolean) => void; caseId: string; setCaseId: (value: string) => void; age: number; setAge: (value: number) => void;
  editing: Fact | null; setEditing: (fact: Fact | null) => void; message: string; setMessage: (value: string) => void; busy: boolean; job: Job | null; voiceState: "idle" | "recording" | "transcribing";
  loadList: () => void; moreCases: () => void; createCase: () => void; changeCase: (id: string) => void; refresh: () => void;
  startRun: (intent: "conversation" | "draft") => void; record: () => void; speak: (text: string, runId: string) => void; stopAudio: () => void;
  newFact: (fact?: Fact) => void; saveFact: () => void; act: (path: string, body: unknown) => Promise<void>; trackDirty: (id: string, value: boolean) => void;
};

function CaseQueue({ props }: { props: CasesPageProps }) {
  const attention = props.cases.filter((item) => item.attention?.needs_attention).length;
  const stale = props.cases.filter((item) => item.attention?.stale_draft || item.handoff_status === "STALE").length;
  return <>
    {!props.current ? <div className="queue-metrics" aria-label="สรุปคิวงาน"><article><span className="metric-icon"><Icon name="cases" /></span><div><strong>{props.cases.length}</strong><span>เคสทั้งหมด</span></div></article><article><span className="metric-icon metric-icon--warning"><Icon name="alert" /></span><div><strong>{attention}</strong><span>มีงานรอตรวจ</span></div></article><article><span className="metric-icon metric-icon--danger"><Icon name="refresh" /></span><div><strong>{stale}</strong><span>ร่างต้องตรวจใหม่</span></div></article></div> : null}
    <aside className="case-list" aria-label="รายการเคส">
      <div className="case-list__heading"><div><span className="eyebrow">คิวงานวันนี้</span><h2>เคสในพื้นที่</h2></div><StatusBadge tone="neutral">{props.cases.length}</StatusBadge></div>
      {!props.cases.length ? <div className="empty-state empty-state--compact"><Icon name="cases" size={28} /><h3>ยังไม่มีเคส</h3><p>เริ่มเคสจำลองเพื่อทดลองรับข้อมูล</p></div> : <div className="case-list__items">{props.cases.map((item) => <button className={`case-item ${props.current?.encounter_id === item.encounter_id ? "case-item--selected" : ""}`} key={item.encounter_id} onClick={() => props.changeCase(item.encounter_id)}>
        <div className="case-item__top"><span className="case-avatar" aria-hidden="true">{item.encounter_id.slice(0, 1).toUpperCase()}</span><span className="case-item__identity"><strong>{item.encounter_id}</strong><small>อายุ {item.age} ปี · รุ่น {item.case_revision}</small></span>{item.attention?.needs_attention ? <span className="attention-dot" aria-label="มีงานที่ต้องตรวจ" /> : null}</div>
        <div className="case-item__status"><StatusBadge tone={item.handoff_status === "CONFIRMED" ? "success" : item.handoff_status === "STALE" ? "warning" : "neutral"}>{handoffLabels[item.handoff_status || "NO_DRAFT"] || "ยังไม่มีร่าง"}</StatusBadge>{item.attention?.pending_proposal_count ? <small>{item.attention.pending_proposal_count} ข้อเสนอรอตรวจ</small> : null}</div>
      </button>)}</div>}
      {props.nextOffset !== null ? <button className="button button--text button--full" onClick={props.moreCases}>โหลดเคสเพิ่ม</button> : null}
    </aside>
  </>;
}

function IntakeStep({ props, pending }: { props: CasesPageProps; pending: number }) {
  const activeJob = !!props.job && ["queued", "running"].includes(props.job.status);
  return <div className="focused-layout focused-layout--intake"><section className="panel conversation-panel">
    <div className="assistant-heading"><span className="assistant-mark"><Icon name="spark" /></span><div><span className="eyebrow">JARVIS assistant</span><h2>สนทนาและรวบรวมข้อมูล</h2><p className="supporting-text">ข้อความจากผู้ช่วยจะไม่กลายเป็นข้อมูลเคสจนกว่าคุณจะตรวจ</p></div><StatusBadge tone={props.caps?.provider === "mock-v2" ? "warning" : "info"}>{props.caps?.provider === "mock-v2" ? "โหมดออฟไลน์" : "รอตรวจโมเดลจริง"}</StatusBadge></div>
    {pending ? <button className="proposal-notice" onClick={() => props.changeStep("facts")}><span className="proposal-notice__icon"><Icon name="alert" /></span><span><strong>มีข้อมูลจากผู้ช่วยรอตรวจ {pending} รายการ</strong><small>เปิดเพื่อตรวจค่าและยืนยันก่อนบันทึก</small></span><Icon name="arrow" /></button> : null}
    <div className="conversation" aria-label="ประวัติการสนทนา">{!props.runs.length ? <div className="empty-state empty-state--conversation"><span><Icon name="spark" /></span><h3>เริ่มจากอาการสำคัญ</h3><p>ลองพิมพ์ “ผู้ป่วยไอมา 2 วัน มีไข้ต่ำ” หรือถามผู้ช่วยว่าควรถามอะไรต่อ</p></div> : props.runs.map((run) => <article className="turn" key={run.run_id}>
      <div className="message-row message-row--user"><div className="message message--user"><span>คุณ</span><p>{run.user_text}</p></div><span className="message-avatar message-avatar--user" aria-hidden="true">{props.session.subject.slice(0, 1).toUpperCase()}</span></div>
      <div className="message-row"><span className="message-avatar" aria-hidden="true"><Icon name="spark" size={16} /></span><div className="message message--assistant"><div><span className="eyebrow">ผู้ช่วย JARVIS</span><StatusBadge tone={run.status === "COMPLETED" ? "success" : "warning"}>{run.status === "COMPLETED" ? "ตอบแล้ว" : "ต้องตรวจสอบ"}</StatusBadge></div><p>{humanizeClinicalText(run.response)}</p>{run.status === "COMPLETED" ? <button className="button button--text button--speak" onClick={() => props.speak(humanizeClinicalText(run.response), run.run_id)}><Icon name="volume" />อ่านคำตอบ</button> : null}</div></div>
    </article>)}</div>
    {!props.message ? <div className="quick-prompts" aria-label="ข้อความแนะนำ"><span>ลองถามผู้ช่วย</span><button type="button" onClick={() => props.setMessage("จากข้อมูลที่มี ควรถามอะไรต่อเพื่อให้รับเคสครบถ้วน?")}>ควรถามอะไรต่อ</button><button type="button" onClick={() => props.setMessage("ช่วยสรุปข้อมูลที่ยืนยันแล้วของเคสนี้แบบสั้น")}>สรุปข้อมูลที่มี</button><button type="button" onClick={() => props.setMessage("ช่วยตรวจว่าข้อมูลสำคัญส่วนใดยังขาดอยู่")}>ตรวจข้อมูลที่ขาด</button></div> : null}
    <div className="composer"><label className="sr-only" htmlFor="assistant-message">ข้อความถึงผู้ช่วย</label><textarea id="assistant-message" aria-label="ข้อความถึงผู้ช่วย" placeholder="พิมพ์ข้อมูล อาการ หรือคำถามที่ต้องการให้ผู้ช่วยช่วยต่อ…" value={props.message} onChange={(event) => props.setMessage(event.target.value)} /><div className="composer__footer"><div className="composer__tools"><button className={`button button--icon ${props.voiceState === "recording" ? "button--recording" : ""}`} aria-label={props.voiceState === "recording" ? "หยุดและถอดเสียง" : props.voiceState === "transcribing" ? "กำลังถอดเสียง" : "กดพูด"} title="กดพูด" disabled={!props.caps?.speech || (props.busy && props.voiceState === "idle")} onClick={props.record}>{props.voiceState === "recording" ? <Icon name="stop" /> : <Icon name="mic" />}</button><span>{props.caps?.speech ? (props.voiceState === "recording" ? "กำลังบันทึกเสียง" : props.voiceState === "transcribing" ? "กำลังถอดเสียง" : "พิมพ์หรือกดพูด") : "พิมพ์ข้อความได้ทันที"}</span></div><button className="button button--primary button--send" aria-label="ส่งข้อความ" disabled={props.busy || !props.message.trim() || activeJob} onClick={() => props.startRun("conversation")}>ส่งให้ผู้ช่วย <Icon name="arrow" /></button></div></div>
    {!props.caps?.speech ? <p className="voice-fallback">ยังไม่ตั้งค่าถอดเสียง การสนทนาด้วยข้อความใช้งานได้ครบทุกขั้นตอน</p> : null}<button className="button button--text stop-audio" onClick={props.stopAudio}><Icon name="volume" />หยุดอ่านเสียง</button>
  </section><aside className="context-rail"><section className="panel compact-summary"><span className="eyebrow">ข้อมูลที่พร้อมใช้</span><div className="summary-number"><strong>{props.facts.length}</strong><span>รายการยืนยันแล้ว</span></div>{props.facts.slice(0, 3).map((fact) => <FactView key={fact.event_id} fact={fact} />)}{props.facts.length > 3 ? <p className="supporting-text">และอีก {props.facts.length - 3} รายการ</p> : null}<button className="button button--secondary button--full" onClick={() => props.changeStep("facts")}>เปิดข้อมูลทั้งหมด</button></section><section className="panel clinical-note"><Icon name="lock" /><div><strong>บุคลากรเป็นผู้ควบคุม</strong><p>ทุกข้อเสนอและร่างต้องผ่านการตรวจยืนยันก่อนใช้งาน</p></div></section></aside></div>;
}

function FactsStep({ props }: { props: CasesPageProps }) {
  const pendingRuns = props.runs.filter((run) => run.case_revision === props.current?.case_revision && run.proposals.some((proposal) => proposal.proposal_id));
  const conflicts = props.facts.filter((fact) => fact.conflicts_with_event_ids?.length);
  const confirmed = props.facts.filter((fact) => !fact.conflicts_with_event_ids?.length);
  return <div className="facts-workspace">
    <section className="section-intro"><div><span className="eyebrow">ตรวจทานก่อนบันทึก</span><h2>ข้อมูลเคส</h2><p>ข้อเสนอจากผู้ช่วยและข้อมูลที่แก้ไขจะไม่ถูกใช้จนกว่าบุคลากรจะยืนยัน</p></div><button className="button button--secondary" onClick={() => props.newFact()}><Icon name="plus" />เพิ่มข้อมูลด้วยตัวเอง</button></section>
    {pendingRuns.length ? <section className="review-zone"><div className="zone-heading"><span className="zone-icon zone-icon--warning"><Icon name="alert" /></span><div><h3>รอตรวจ {pendingRuns.reduce((sum, run) => sum + run.proposals.length, 0)} รายการ</h3><p>ตรวจประเภท ค่า และหน่วยก่อนบันทึกแบบชุด</p></div></div>{pendingRuns.map((run) => <Proposals key={run.run_id} run={run} onDirty={(value) => props.trackDirty(run.run_id, value)} revision={props.current!.case_revision} act={props.act} />)}</section> : <section className="completion-card"><span><Icon name="check" /></span><div><h3>ตรวจข้อมูลเรียบร้อย</h3><p>ข้อมูลที่ยืนยันแล้วพร้อมใช้สร้างร่างส่งต่อ</p></div><button className="button button--primary" disabled={!confirmed.length || props.busy} onClick={() => { props.changeStep("draft"); props.startRun("draft"); }}>เตรียมร่างส่งต่อ <Icon name="arrow" /></button></section>}
    {conflicts.length ? <section className="review-zone review-zone--danger"><div className="zone-heading"><span className="zone-icon zone-icon--danger"><Icon name="alert" /></span><div><h3>ต้องตรวจความสอดคล้อง</h3><p>ข้อมูลต่อไปนี้ขัดแย้งกับข้อมูลอื่นในเคส</p></div></div><div className="fact-grid">{conflicts.map((fact) => <FactView key={fact.event_id} fact={fact} onEdit={props.newFact} />)}</div></section> : null}
    <section className="panel confirmed-zone"><div className="section-heading"><div><span className="eyebrow">พร้อมใช้สร้างร่าง</span><h2>ข้อมูลที่ยืนยันแล้ว</h2></div><StatusBadge tone="success">{confirmed.length} รายการ</StatusBadge></div>{confirmed.length ? <div className="fact-grid">{confirmed.map((fact) => <FactView key={fact.event_id} fact={fact} onEdit={props.newFact} />)}</div> : <div className="empty-state empty-state--compact"><Icon name="file" size={28} /><h3>ยังไม่มีข้อมูลยืนยัน</h3><p>กลับไปรับข้อมูลหรือเพิ่มข้อมูลด้วยตัวเอง</p></div>}</section>
  </div>;
}

function DraftStep({ props }: { props: CasesPageProps }) {
  const latest = props.drafts.at(-1);
  const older = props.drafts.length > 1 ? props.drafts.slice(0, -1).reverse() : [];
  if (!latest) return <section className="empty-state empty-state--hero draft-empty"><span className="empty-state__mark"><Icon name="file" size={28} /></span><span className="eyebrow">ขั้นตรวจร่าง</span><h2>ยังไม่มีร่างส่งต่อ</h2><p>ระบบจะสร้างร่างจากข้อมูลที่ยืนยันแล้ว ณ revision ปัจจุบัน เพื่อให้แพทย์ตรวจเนื้อหาและหลักฐาน</p><button className="button button--primary" disabled={props.busy || !props.facts.length} onClick={() => props.startRun("draft")}><Icon name="spark" />เตรียมร่างส่งต่อ</button>{!props.facts.length ? <p className="field-hint">ต้องมีข้อมูลยืนยันอย่างน้อยหนึ่งรายการก่อนสร้างร่าง</p> : null}</section>;
  return <div className="draft-focused"><section className="section-intro"><div><span className="eyebrow">ร่างล่าสุด</span><h2>ตรวจเนื้อหาและหลักฐาน</h2><p>ยืนยันได้เฉพาะร่างที่อ้างอิงข้อมูล revision ปัจจุบันและไม่มีการแก้ไขค้างอยู่</p></div><button className="button button--secondary" disabled={props.busy} onClick={() => props.startRun("draft")}><Icon name="refresh" />สร้างจากข้อมูลล่าสุด</button></section><Review key={latest.draft_id} draft={latest} revision={props.current!.case_revision} canReview={props.session.role === "physician"} act={props.act} onDirty={(value) => props.trackDirty(latest.draft_id, value)} />{older.length ? <details className="panel version-timeline"><summary>ประวัติร่างก่อนหน้า {older.length} รายการ</summary><ol>{older.map((draft) => <li key={draft.draft_id}><span className="timeline-dot" /><div><strong>ร่างฉบับที่ {draft.draft_revision}</strong><p>{draft.effective ? "เคยยืนยันแล้ว" : "เก็บเป็นประวัติ"} · อ้างอิงข้อมูลรุ่น {draft.case_revision}</p></div><StatusBadge tone={draft.effective ? "success" : "neutral"}>{draft.effective ? "ยืนยันแล้ว" : "ประวัติ"}</StatusBadge></li>)}</ol></details> : null}</div>;
}

export function CasesPage(props: CasesPageProps) {
  const pending = props.current ? pendingProposalCount(props.runs, props.current.case_revision) : 0;
  const latest = props.drafts.at(-1);
  return <>
    <div className="case-toolbar"><form className="search-form" role="search" onSubmit={(event) => { event.preventDefault(); props.loadList(); }}><label className="sr-only" htmlFor="case-search">ค้นหารหัสเคส</label><div className="search-field"><Icon name="search" /><input id="case-search" type="search" placeholder="ค้นหารหัสเคสจำลอง" value={props.query} onChange={(event) => props.setQuery(event.target.value)} /></div><label className="sr-only" htmlFor="case-status">สถานะร่าง</label><select id="case-status" value={props.caseStatus} onChange={(event) => props.setCaseStatus(event.target.value)}><option value="">ทุกสถานะ</option>{Object.entries(handoffLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="button button--secondary">ค้นหา</button></form><button className="button button--primary button--create" onClick={() => props.setNewCaseOpen(!props.newCaseOpen)}><Icon name="plus" />เริ่มเคสจำลอง</button></div>
    {props.newCaseOpen ? <form className="panel create-case" onSubmit={(event) => { event.preventDefault(); props.createCase(); }}><div className="section-heading"><div><span className="eyebrow">ข้อมูลสังเคราะห์</span><h2>เริ่มเคสจำลองใหม่</h2><p className="supporting-text">ใช้รหัสที่จำง่ายและไม่เกี่ยวข้องกับข้อมูลผู้ป่วยจริง</p></div><button type="button" className="button button--text" onClick={() => props.setNewCaseOpen(false)}>ปิด</button></div><div className="form-grid"><label>รหัสเคส<input required pattern="[A-Za-z0-9_-]+" value={props.caseId} onChange={(event) => props.setCaseId(event.target.value)} placeholder="เช่น demo-001" /></label><label>อายุผู้ป่วยสมมติ<input required type="number" min="18" max="120" value={props.age} onChange={(event) => props.setAge(Number(event.target.value))} /></label></div><label className="check-control"><input required type="checkbox" /><span>ยืนยันว่าเคสนี้ไม่มีข้อมูลที่ระบุตัวผู้ป่วยจริง</span></label><button className="button button--primary" disabled={props.busy}>สร้างและเปิดเคส</button></form> : null}
    <div className={`case-layout ${!props.current ? "case-layout--queue" : ""}`}><div className="queue-column"><CaseQueue props={props} /></div>{!props.current ? <section className="empty-state empty-state--hero"><span className="empty-state__mark"><Icon name="spark" size={28} /></span><span className="eyebrow">พื้นที่รับเคสพร้อมใช้งาน</span><h2>เลือกเคสเพื่อเริ่มทำงาน</h2><p>ผู้ช่วยจะช่วยเก็บข้อมูลอย่างเป็นขั้นตอน โดยทุกข้อมูลและร่างส่งต่อต้องผ่านการตรวจจากบุคลากร</p><ol><li><span>1</span><div><strong>รับข้อมูล</strong><small>สนทนาและระบุอาการสำคัญ</small></div></li><li><span>2</span><div><strong>ตรวจทาน</strong><small>ยืนยันเฉพาะข้อมูลที่ถูกต้อง</small></div></li><li><span>3</span><div><strong>ส่งให้แพทย์</strong><small>สร้างร่างและตรวจหลักฐาน</small></div></li></ol></section> : <div className="case-content">
      <section className="case-overview" aria-labelledby="case-title"><div className="case-overview__identity"><span className="case-overview__avatar" aria-hidden="true">{props.current.encounter_id.slice(0, 1).toUpperCase()}</span><div><span className="eyebrow">เคสสังเคราะห์</span><h2 id="case-title">{props.current.encounter_id}</h2><p>ผู้ป่วยสมมติอายุ {props.current.age} ปี · ข้อมูลรุ่น {props.current.case_revision}</p></div></div><div className="case-overview__metrics"><div><strong>{props.facts.length}</strong><span>ข้อมูลยืนยัน</span></div><div><strong>{pending}</strong><span>ข้อเสนอรอตรวจ</span></div><div><strong>{latest ? `ฉบับ ${latest.draft_revision}` : "—"}</strong><span>ร่างล่าสุด</span></div></div><button className="button button--secondary button--refresh" onClick={props.refresh}><Icon name="refresh" />โหลดข้อมูลล่าสุด</button></section>
      <nav className="clinical-stepper" aria-label="ขั้นตอนจัดการเคส">{clinicalSteps.map((item, index) => { const state = stepState(item.id, props.facts, props.runs, props.drafts, props.current!.case_revision); return <button key={item.id} className={`clinical-step clinical-step--${state} ${props.step === item.id ? "clinical-step--selected" : ""}`} aria-current={props.step === item.id ? "step" : undefined} onClick={() => props.changeStep(item.id)}><span className="clinical-step__number">{state === "complete" ? <Icon name="check" size={16} /> : index + 1}</span><span><strong>{item.label}</strong><small>{state === "attention" ? "ต้องตรวจ" : item.description}</small></span></button>; })}</nav>
      <div className="focused-stage">{props.step === "intake" ? <IntakeStep props={props} pending={pending} /> : props.step === "facts" ? <FactsStep props={props} /> : <DraftStep props={props} />}</div><History key={`${props.current.encounter_id}:${props.current.case_revision}`} encounter={props.current.encounter_id} />
    </div>}</div>
    {props.editing ? <SideSheet title={props.editing.supersedes_event_id ? "แก้ไขข้อมูลเดิม" : "เพิ่มข้อมูล"} description="ตรวจประเภท สถานะ และค่าก่อนบันทึกเข้าสู่เคส" onClose={() => props.setEditing(null)}><form onSubmit={(event) => { event.preventDefault(); props.saveFact(); }}><FactEditor key={props.editing.event_id} fact={props.editing} onChange={props.setEditing} /><div className="sheet-actions"><button className="button button--primary" disabled={props.busy}>ตรวจแล้ว บันทึกข้อมูล</button><button type="button" className="button button--secondary" onClick={() => props.setEditing(null)}>ยกเลิก</button></div></form></SideSheet> : null}
  </>;
}
