"""Render research/base_model/selection_matrix.json to SELECTION_MATRIX.md (deterministic).

    python -m research.base_model.render --out research/base_model/SELECTION_MATRIX.md

Benchmark numbers are ranked only inside one `comparable_group` and only for the same
(benchmark, metric). Numbers from different groups are listed, never ranked against each other.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
MATRIX_PATH = HERE / "selection_matrix.json"
DEFAULT_OUT = HERE / "SELECTION_MATRIX.md"


def load_matrix(path: Path = MATRIX_PATH) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _fmt(value: Any) -> str:
    if value is None:
        return "null (not reported)"
    if value is True:
        return "yes"
    if value is False:
        return "no"
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, dict):
        return "; ".join(f"{k}: {_fmt(v)}" for k, v in value.items())
    return str(value).replace("|", "/")


def _cell(text: str) -> str:
    return text.replace("|", "/").replace("\n", " ")


def _sources(cell: dict[str, Any]) -> str:
    urls = [cell["source_url"]] + [s["source_url"] for s in cell.get("additional_sources", [])]
    return " ".join(f"<{u}>" for u in urls)


def benchmark_groups(matrix: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    """comparable_group -> entries (each tagged with its candidate)."""
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in matrix["rows"]:
        for entry in row["cells"]["medical_benchmarks"]["value"]:
            groups[entry["comparable_group"]].append({**entry, "candidate": row["display_name"]})
    return dict(sorted(groups.items()))


def rankings(matrix: dict[str, Any]) -> list[dict[str, Any]]:
    """Within-group rankings for (group, benchmark, metric, setting) keys with >= 2 candidates.

    Each item: {group, benchmark, metric, setting, order: [(candidate, value), ...]} sorted high to low.
    A key never spans groups, so non-comparable numbers are never ranked together.
    """
    out = []
    for group, entries in benchmark_groups(matrix).items():
        keyed: dict[tuple[str, str, str], list[tuple[str, float]]] = defaultdict(list)
        for e in entries:
            keyed[(e["benchmark"], e["metric"], e["setting"])].append((e["candidate"], e["value"]))
        for (bench, metric, setting), vals in sorted(keyed.items()):
            if len({c for c, _ in vals}) >= 2:
                order = sorted(vals, key=lambda cv: (-cv[1], cv[0]))
                out.append({"group": group, "benchmark": bench, "metric": metric, "setting": setting, "order": order})
    return out


def render(matrix: dict[str, Any]) -> str:
    rows = matrix["rows"]
    lines: list[str] = []
    add = lines.append
    add("# Base model selection matrix (slice s9)")
    add("")
    add("<!-- Generated by `python -m research.base_model.render` from selection_matrix.json. Do not edit by hand. -->")
    add("")
    add(f"> {matrix['claim_boundary']}")
    add("")
    add(f"Owner: {matrix['owner']}. Sources retrieved on {matrix['retrieved_on']}. Every cell cites a primary source "
        "(official model card, license text, technical report, or official GitHub). `null` means the source was checked "
        "and the value is not reported there.")
    add("")
    add(f"**Status: `{matrix['status']}`. Final selection: `{json.dumps(matrix['final_selection'])}`.** "
        "No winner is declared. The choice follows the preliminary experiments (proposal 2.3), scored with the rubric below.")
    add("")
    add("## Candidates")
    add("")
    for row in rows:
        add(f"- **{row['display_name']}**: {row['variant_note']}")
    add("")
    for i, col in enumerate(matrix["columns"], 1):
        if col["id"] == "medical_benchmarks":
            continue
        add(f"## {i}. {col['title']}")
        add("")
        add("| Candidate | Value | Note | Sources (retrieved) |")
        add("|---|---|---|---|")
        for row in rows:
            cell = row["cells"][col["id"]]
            add(f"| {row['display_name']} | {_cell(_fmt(cell['value']))} | {_cell(cell['note'])} | "
                f"{_sources(cell)} ({cell['retrieved_on']}) |")
        add("")
    bench_idx = [c["id"] for c in matrix["columns"]].index("medical_benchmarks") + 1
    add(f"## {bench_idx}. Reported medical benchmarks")
    add("")
    add("Numbers are grouped by `comparable_group` (same source, harness and setting). They are ranked only inside a group "
        "and only for the same benchmark, metric and setting. Numbers from different groups are not comparable and are "
        "never ranked against each other.")
    add("")
    for row in rows:
        cell = row["cells"]["medical_benchmarks"]
        if not cell["value"]:
            add(f"- {row['display_name']}: none reported. {cell['note']} Checked: <{cell['source_url']}> ({cell['retrieved_on']}).")
    add("")
    for group, entries in benchmark_groups(matrix).items():
        add(f"### Group: {group}")
        add("")
        add("| Candidate | Benchmark | Split | Metric | Value | Setting | Source |")
        add("|---|---|---|---|---|---|---|")
        for e in entries:
            add(f"| {e['candidate']} | {e['benchmark']} | {e['split']} | {e['metric']} | {e['value']} | {e['setting']} | "
                f"<{e['source_url']}> ({e['retrieved_on']}) |")
        add("")
    add("### Within-group rankings")
    add("")
    ranked = rankings(matrix)
    if not ranked:
        add("None. No comparable group contains the same benchmark, metric and setting for two or more candidates, so no "
            "cross-candidate ranking is possible from reported numbers. Candidates are compared in the preliminary experiments.")
    for r in ranked:
        order = " > ".join(f"{c} ({v})" for c, v in r["order"])
        add(f"- [{r['group']}] {r['benchmark']} / {r['metric']} / {r['setting']}: {order}")
    add("")
    rub = matrix["rubric"]
    add("## Pre-declared selection rubric")
    add("")
    add(f"Declared on {rub['declared_on']}, before any preliminary fine-tune result exists (no file under `research/results/`).")
    add("")
    add(f"Selection data: {rub['selection_data']}")
    add("")
    add("Hard constraints (a candidate failing any one is excluded):")
    add("")
    for h in rub["hard_constraints"]:
        add(f"- {h}")
    add("")
    add("| Criterion | Weight | Measure |")
    add("|---|---|---|")
    for c in rub["criteria"]:
        add(f"| {c['id']} | {c['weight']:.2f} | {c['measure']} |")
    add(f"| **total** | **{sum(c['weight'] for c in rub['criteria']):.2f}** | |")
    add("")
    add("Tie-breaks, in order: " + " ".join(f"({i}) {t}" for i, t in enumerate(rub["tie_breaks"], 1)))
    add("")
    add(f"Fairness: {rub['comparison_fairness']}")
    add("")
    add("## Decisions needed (humans)")
    add("")
    for d in matrix["decisions_needed"]:
        add(f"- **{d['id']}** ({', '.join(d['candidates'])}): {d['question']}")
    add("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--matrix", type=Path, default=MATRIX_PATH)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)
    args.out.write_text(render(load_matrix(args.matrix)), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
