"""Slice i2: the Case Graph over S1r decision points (I2-A04, A05, A17). Synthetic, offline, mock only.

The dataset is generated by the S1r factory CLI in a subprocess (no ``data_factory`` import under casegraph/).
The test split is never compiled here (it runs only inside the frozen evaluation run).
"""

from __future__ import annotations

import subprocess
import sys
from datetime import timedelta
from pathlib import Path

import pytest

from casegraph.compiler import build_snapshot, compile_graph
from casegraph.data import IntakeTranscript, Turn, Vitals
from casegraph.executor import Executor
from casegraph.providers import mock_gateways
from casegraph.reader_text import visible_turns
from casegraph.run_s1r import check_graph, run
from casegraph.sources.s1r import load_split
from casegraph.store import MemoryStateStore, OutputStore, next_version, replay
from casegraph.types import NodeType

ROOT = Path(__file__).resolve().parents[2]
SEED = 20260926


@pytest.fixture(scope="module")
def dataset(s1r_dataset) -> Path:
    return s1r_dataset


def _execute(snap, gateways=None):
    gateways = gateways or mock_gateways()
    ex = Executor(gateways, OutputStore(), MemoryStateStore())
    return ex, ex.run_sync(compile_graph(build_snapshot(snap.items, snap.T, snap.patient_ref)))


def test_s1r_compile_execute(dataset):
    summary = run(dataset, ["dev"], replay_check=True, no_cache=True)
    dev = summary["splits"]["dev"]
    assert summary["pass"] is True
    assert dev["n_dp"] == 80 and dev["n_patients"] == 36 and dev["compiled"] == 80
    assert dev["compile_errors"] == {} and dev["node_errors"] == 0 and dev["invariant_violations"] == {}
    assert sum(dev["graph_shape_histogram"].values()) == 80
    assert all("red_flag" in s and s.endswith("human_checkpoint") for s in dev["graph_shape_histogram"])
    assert summary["label"] == "System Evaluation on synthetic data — not clinical performance"
    assert summary["dataset"]["data_class"] == "synthetic"


def test_graph_time_valid(dataset):
    for snap in load_split(dataset, "dev")[:20]:
        _, graph = _execute(snap)
        assert all(r.available_at_time <= snap.T for r in graph.evidence)
        rt = graph.by_type(NodeType.READER_TEXT)
        cited = [t for f in rt.output["Findings"]["facts"] + rt.output["Findings"]["intake"]
                 for t in f["evidence_turns"]]
        assert cited, snap.dp_id
        assert check_graph(snap, graph) == []


def test_planted_future_excluded(dataset):
    snap = next(s for s in load_split(dataset, "dev") if not any(
        i.data_type == "IntakeTranscript" and "หน้าอก" in " ".join(t.text for t in i.turns) for i in s.items))
    tx = next(i for i in snap.items if isinstance(i, IntakeTranscript))
    later = snap.T + timedelta(minutes=5)
    # 1) a future item: an abnormal vital available after T
    future_vitals = Vitals(item_id="PLANTED-FUTURE-VS", patient_ref=snap.patient_ref, event_time=later,
                           available_at_time=later, source="synthetic", provenance="i2 planted future item",
                           version="1", data_class="synthetic", hr=190.0, sbp=70.0, spo2=80.0)
    # 2) a future turn: a transcript continuation whose chest-pain turn is spoken after T
    future_turn = Turn(turn_index=max(t.turn_index for t in tx.turns) + 1, speaker="patient",
                       text="เจ็บหน้าอกขึ้นมาทันทีค่ะ", spoken_at=later)
    future_tx = tx.model_copy(update={"item_id": "PLANTED-FUTURE-TX", "available_at_time": later,
                                      "turns": (*tx.turns, future_turn)})
    items = (*snap.items, future_vitals, future_tx)
    snapshot = build_snapshot(items, snap.T, snap.patient_ref)
    ex = Executor(mock_gateways(), OutputStore(), MemoryStateStore())
    graph = ex.run_sync(compile_graph(snapshot))
    ids = {r.item_id for r in graph.evidence}
    excluded = [x not in ids for x in ("PLANTED-FUTURE-VS", "PLANTED-FUTURE-TX")]
    assert excluded == [True, True]  # 2/2
    alerts = graph.node("red_flag").output["Alerts"]
    assert "RF-CHEST" not in {a["rule_id"] for a in alerts["alerts"]}
    facts = graph.node("reader_text").output["Findings"]["facts"]
    assert all(t["turn_index"] != future_turn.turn_index or t["item_id"] != "PLANTED-FUTURE-TX"
               for f in facts for t in f["evidence_turns"])
    # defence in depth inside Reader:Text: a turn after T is never read even if its item were visible
    assert future_turn not in visible_turns(future_tx, snap.T)


def test_replay_zero_calls(dataset):
    snaps = load_split(dataset, "dev")[:10]
    gateways = mock_gateways()
    outputs, state = OutputStore(), MemoryStateStore()
    ex = Executor(gateways, outputs, state)
    graphs = []
    for snap in snaps:
        # one Output Store for all DPs; one graph per patient version
        v, p = next_version(state, snap.patient_ref)
        graphs.append(ex.run_sync(compile_graph(build_snapshot(snap.items, snap.T, snap.patient_ref),
                                                version=v, parent_version=p)))
    calls, execs = sum(g.calls for g in gateways.values()), sum(ex.node_executions.values())
    for g in graphs:
        again = replay(g.graph_id, outputs, state)
        assert [n.output_sha256 for n in again.nodes] == [n.output_sha256 for n in g.nodes]
    assert sum(g.calls for g in gateways.values()) == calls
    assert sum(ex.node_executions.values()) == execs
    # a no-cache rerun reproduces every node output hash
    for snap, g in zip(snaps, graphs):
        _, fresh = _execute(snap)
        assert [n.output_sha256 for n in fresh.nodes] == [n.output_sha256 for n in g.nodes]


def test_run_s1r_cli_refuses_test_split(dataset):
    r = subprocess.run([sys.executable, "-m", "casegraph", "run-s1r", "--dataset", str(dataset), "--splits", "test"],
                       cwd=ROOT, capture_output=True, text=True, env={"PYTHONPATH": f"{ROOT}:{ROOT / 'backend'}",
                                                                      "PATH": "/usr/bin:/bin"})
    assert r.returncode != 0 and "frozen evaluation run" in r.stderr
