#!/usr/bin/env python3
"""Regenerate requirements.lock (hashed) with torch taken from the PyTorch CPU page.

uv does not emit hashes for --find-links packages, so this script compiles the lock with uv and then
adds the sha256 hashes published on the PyTorch CPU page for the pinned torch version. Every other
package is resolved from PyPI with uv's own hashes. Network is needed only when re-locking.

    python3 scripts/lock_requirements.py
"""

from __future__ import annotations

import re
import subprocess
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "requirements.lock"
TORCH_PAGE = "https://download.pytorch.org/whl/cpu/torch/"
UV_CMD = [
    "uv", "pip", "compile", "requirements.in", "--universal", "--python-version", "3.11",
    "--generate-hashes", "--find-links", TORCH_PAGE, "--emit-find-links", "--refresh",
    "-o", "requirements.lock",
]


def torch_hashes(page: str, version: str) -> list[str]:
    """sha256 of every wheel on the page whose version is exactly `version` (e.g. 2.14.0 or 2.14.0+cpu)."""
    quoted = re.escape(version.replace("+", "%2B"))
    pattern = re.compile(rf"torch-{quoted}-[^\"#<]+\.whl#sha256=([0-9a-f]{{64}})")
    return sorted(set(pattern.findall(page)))


def main() -> int:
    subprocess.run(UV_CMD, cwd=ROOT, check=True)
    with urllib.request.urlopen(TORCH_PAGE, timeout=60) as resp:  # noqa: S310 (fixed https URL)
        page = resp.read().decode()
    lines = LOCK.read_text().splitlines()
    out: list[str] = []
    for line in lines:
        m = re.match(r"^torch==(\S+)( ; .*)?$", line)
        if not m:
            out.append(line)
            continue
        hashes = torch_hashes(page, m.group(1))
        if not hashes:
            raise SystemExit(f"no wheels for torch=={m.group(1)} on {TORCH_PAGE}")
        out.append(line + " \\")
        out.extend(f"    --hash=sha256:{h}" + (" \\" if i < len(hashes) - 1 else "") for i, h in enumerate(hashes))
    header = "# Generated by scripts/lock_requirements.py (uv compile + torch hashes from the PyTorch CPU page)."
    LOCK.write_text(header + "\n" + "\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
